/* =====================================================================================
   MODERN HISTORY — QUESTION BANK
   -------------------------------------------------------------------------------------
   This file ONLY contains Modern History questions. Edit ONLY this file to add/update
   Modern History questions — you never need to open index.html or any other subject file.

   HOW TO ADD ONE QUESTION:
   Copy a line like the example below, paste it inside the right "sets" array
   (before the closing "]}"), and edit the text:
       {q:"Your question?", opts:["Option A","Option B","Option C","Option D"], correct:1}
   correct: 0 = 1st option is right, 1 = 2nd, 2 = 3rd, 3 = 4th.
   Every question needs a comma "," after it EXCEPT the very last one in that set.

   HOW TO ADD A WHOLE NEW SET (e.g. "Modern History Set 3"):
   Copy an entire { title: "...", questions: [ ... ] } block below, paste it after
   the last set (still inside the outer "sets: [ ]"), rename the title, and replace
   the questions inside.

   Save this file, then re-upload it to your hosting along with index.html and the
   rest of the "questions" folder. index.html itself never needs to change.
   ===================================================================================== */

     const SUBJECT_MODERNHISTORY = {
  name: "Modern History",
  icon: "🗽",
  sets: [
    { title: "Modern History Set 1", questions: [
      {q:"When did India get independence?", opts:["15th August 1947","26th January 1947","2nd October 1947","14th August 1947"], correct:0},
      {q:"Official Independence Day Celebration takes place at:", opts:["India Gate, Delhi","Red Fort, Delhi","Rashtrapati Bhavan, Delhi","Parliament House, Delhi"], correct:1},
      {q:"Who stated, \"Tum mujhe khoon do, mein tumhe azadi doonga\"?", opts:["Jawaharlal Nehru","Bal Gangadhar Tilak","Subhas Chandra Bose","Bhagat Singh"], correct:2},
      {q:"The \"Iron Man of India\" is the title given to:", opts:["Jawaharlal Nehru","Vallabhbhai Patel","Lal Bahadur Shastri","Rajendra Prasad"], correct:1},
      {q:"Who became India's first Governor-General following its independence?", opts:["C. Rajagopalachari","Lord Wavell","Lord Mountbatten","Lord Linlithgow"], correct:2},
      {q:"Which Indian prince was the first to accept the Subsidiary Alliance proposed by Lord Wellesley in 1798?", opts:["Nizam of Hyderabad","Peshwa Baji Rao II","Nawab of Awadh","Tipu Sultan"], correct:0},
      {q:"When did Mahatma Gandhi issue the challenge \"Do or Die\"?", opts:["During the Non-Cooperation Movement in 1920","During the Civil Disobedience Movement in 1930","During the Quit India Movement in 1942","During the Salt March in 1930"], correct:2},
      {q:"When did the Jallianwala Bagh massacre take place?", opts:["13th April 1919","13th March 1919","13th April 1920","10th April 1919"], correct:0},
      {q:"Who gave the slogan \"Dilli Chalo\" or \"March to Delhi\"?", opts:["Rash Behari Bose","Subhas Chandra Bose","Mohan Singh","Jawaharlal Nehru"], correct:1},
      {q:"Who wrote the renowned book \"The Discovery of India\"?", opts:["Mahatma Gandhi","Jawaharlal Nehru","Rabindranath Tagore","Sarojini Naidu"], correct:1},
      {q:"Who was India's final Mughal emperor?", opts:["Shah Alam II","Akbar II","Bahadur Shah Zafar (Bahadur Shah II)","Muhammad Shah"], correct:2},
      {q:"Who was the author of the revolutionary book \"Philosophy of the Bomb\"?", opts:["Bhagat Singh","Bhagwati Charan Vohra","Chandrashekhar Azad","Sukhdev"], correct:1},
      {q:"Who was India's first President?", opts:["Dr. Rajendra Prasad","Dr. S. Radhakrishnan","Jawaharlal Nehru","Zakir Husain"], correct:0},
      {q:"What do the three main colors on India's national flag stand for?", opts:["Saffron (Courage and Sacrifice), White (Peace and Truth), Green (Faith and Prosperity)","Saffron (Unity), White (Purity), Green (Progress)","Saffron (Bravery), White (Peace), Green (Fertility)","Saffron (Sacrifice), White (Honesty), Green (Growth)"], correct:0},
      {q:"Who raised the national flag on 15th August 1947 at the Red Fort?", opts:["Mahatma Gandhi","Jawaharlal Nehru","Dr. Rajendra Prasad","Lord Mountbatten"], correct:1},
      {q:"When did the Constitution of India come into full effect?", opts:["15th August 1947","26th November 1949","26th January 1950","2nd October 1950"], correct:2},
      {q:"Who is widely recognized as the chief architect of the Indian Constitution?", opts:["Jawaharlal Nehru","Dr. B. R. Ambedkar","Sardar Patel","Rajendra Prasad"], correct:1},
      {q:"Who was the first and only Indian Governor-General of independent India?", opts:["C. Rajagopalachari","Dr. Rajendra Prasad","Lord Mountbatten","Vallabhbhai Patel"], correct:0},
      {q:"Who designed the primary layout of the modern Indian National Flag?", opts:["Pingali Venkayya","Madam Bhikaji Cama","Surendranath Banerjee","Abanindranath Tagore"], correct:0},
      {q:"Who founded the National Council of Education in Bengal in 1906?", opts:["Aurobindo Ghosh","Satish Chandra Mukherjee","Bipin Chandra Pal","Rabindranath Tagore"], correct:1},
      {q:"What is the name of the international boundary line demarcated between India and Pakistan in 1947?", opts:["McMahon Line","Durand Line","Radcliffe Line","Line of Control"], correct:2},
      {q:"On what date and by whom was Mahatma Gandhi assassinated?", opts:["30th January 1948 by Nathuram Godse","15th August 1947 by Nathuram Godse","26th January 1948 by Nathuram Godse","30th January 1947 by Nathuram Godse"], correct:0},
      {q:"What is the full standard time duration specified for playing the Indian National Anthem?", opts:["52 seconds","40 seconds","60 seconds","45 seconds"], correct:0},
      {q:"On which exact date was the Indian Tricolor officially adopted as the National Flag of India?", opts:["22nd July 1947","15th August 1947","26th January 1947","14th August 1947"], correct:0},
      {q:"What four animals are depicted on the base abacus of the National Emblem of India?", opts:["Lion, Elephant, Horse, and bull","Lion, Tiger, Elephant, and Horse","Elephant, Horse, Bull, and Deer","Lion, Bull, Horse, and Deer"], correct:0}
    ]},
    { title: "Modern History Set 2", questions: [
      {q:"Who was the Prime Minister of Great Britain when India gained independence in 1947?", opts:["Winston Churchill","Clement Attlee","Neville Chamberlain","Stanley Baldwin"], correct:1},
      {q:"Who composed the patriotic poem \"Vande Mataram\" in his novel Anandamath?", opts:["Rabindranath Tagore","Bankim Chandra Chattopadhyay","Sarat Chandra Chattopadhyay","Michael Madhusudan Dutt"], correct:1},
      {q:"What is the official National Emblem of India derived from?", opts:["Lion Capital of Ashoka at Sarnath","Great Stupa at Sanchi","Ajanta Caves","Red Fort"], correct:0},
      {q:"Who is universally revered as the \"Father of the Nation\" in India?", opts:["Jawaharlal Nehru","Subhas Chandra Bose","Mahatma Gandhi","Sardar Patel"], correct:2},
      {q:"Who took oath as the first Prime Minister of independent India?", opts:["Jawaharlal Nehru","Sardar Patel","Rajendra Prasad","C. Rajagopalachari"], correct:0},
      {q:"Who composed the original Bengali verses of India's National Anthem, \"Jana Gana Mana\"?", opts:["Bankim Chandra Chattopadhyay","Rabindranath Tagore","Kazi Nazrul Islam","Sarojini Naidu"], correct:1},
      {q:"In which year was the Indian National Congress established?", opts:["1875","1885","1905","1915"], correct:1},
      {q:"In which city was the first session of the Indian National Congress held?", opts:["Mumbai (then Bombay)","Calcutta","Madras","Delhi"], correct:0},
      {q:"Which commission was formed in 1902 to review the working of universities in British India?", opts:["Hunter Commission","Raleigh Commission","Simon Commission","Sadler Commission"], correct:1},
      {q:"From which ashram did Mahatma Gandhi begin his historic Dandi March?", opts:["Sevagram Ashram","Sabarmati Ashram, Ahmedabad","Phoenix Ashram","Tolstoy Farm"], correct:1},
      {q:"In which year did the historic Dandi March take place?", opts:["1928","1930","1932","1942"], correct:1},
      {q:"What is the official National Song of India?", opts:["Jana Gana Mana","Vande Mataram","Sare Jahan Se Achha","Ae Mere Watan Ke Logo"], correct:1},
      {q:"Which Indian poet and leader is known as the \"Nightingale of India\" (Bharat Kokila)?", opts:["Sarojini Naidu","Annie Besant","Kasturba Gandhi","Vijaya Lakshmi Pandit"], correct:0},
      {q:"Who was the first woman President of the Indian National Congress (1917 Calcutta Session)?", opts:["Sarojini Naidu","Annie Besant","Nellie Sengupta","Vijaya Lakshmi Pandit"], correct:1},
      {q:"Who was the first Indian woman President of the Indian National Congress (1925 Kanpur Session)?", opts:["Annie Besant","Sarojini Naidu","Nellie Sengupta","Kamala Nehru"], correct:1},
      {q:"Which prominent freedom fighter earned the moniker \"Grand Old Man of India\"?", opts:["Dadabhai Naoroji","Gopal Krishna Gokhale","Surendranath Banerjee","W. C. Bonnerjee"], correct:0},
      {q:"Who founded the All India Forward Bloc within the Congress party in 1939?", opts:["Jawaharlal Nehru","Subhas Chandra Bose","Rash Behari Bose","Bal Gangadhar Tilak"], correct:1},
      {q:"What is the literal English translation of the national motto \"Satyameva Jayate\"?", opts:["Truth alone triumphs","God is truth","Unity in truth","Truth is eternal"], correct:0},
      {q:"From which ancient Upanishad is the national motto \"Satyameva Jayate\" inscribed on the National Emblem taken?", opts:["Katha Upanishad","Mundaka Upanishad","Isha Upanishad","Chandogya Upanishad"], correct:1},
      {q:"Which courageous queen led the forces of Jhansi against the British East India Company during the 1857 Revolt?", opts:["Rani Lakshmibai","Rani Padmini","Rani Ahilyabai Holkar","Rani Chennamma"], correct:0},
      {q:"In which year was the Partition of Bengal enacted by Viceroy Lord Curzon?", opts:["1900","1905","1909","1911"], correct:1},
      {q:"Which major nationalist movement was launched in 1905 to protest the Partition of Bengal?", opts:["Non-Cooperation Movement","Swadeshi Movement","Quit India Movement","Civil Disobedience Movement"], correct:1},
      {q:"Who coined and popularized the greeting \"Jai Hind\"?", opts:["Jawaharlal Nehru","Subhas Chandra Bose","Bhagat Singh","Mahatma Gandhi"], correct:1},
      {q:"Which freedom fighter was widely given the title \"Lion of Punjab\" (Sher-e-Punjab)?", opts:["Lala Lajpat Rai","Bhagat Singh","Sardar Ajit Singh","Udham Singh"], correct:0},
      {q:"Which British officer ordered the troops to open fire on the unarmed gathering at Jallianwala Bagh?", opts:["Michael O'Dwyer","Brigadier-General Reginald Dyer","Lord Chelmsford","General Harry Cox"], correct:1}
    ]},
    { title: "Modern History Set 3", questions: [
      {q:"Which all-British parliamentary panel visited India in 1928 and faced widespread \"Go Back\" protests?", opts:["Hunter Commission","Simon Commission","Raleigh Commission","Cripps Mission"], correct:1},
      {q:"In which year was the Non-Cooperation Movement launched by Mahatma Gandhi?", opts:["1918","1920","1922","1924"], correct:1},
      {q:"Who co-founded the Swaraj Party inside the Congress in 1923?", opts:["Chittaranjan Das and Motilal Nehru","Bal Gangadhar Tilak and Gokhale","Jawaharlal Nehru and Bose","Rajendra Prasad and Patel"], correct:0},
      {q:"What main demand was formally declared in the 1929 Lahore Session of the INC?", opts:["Dominion Status","Purna Swaraj (Complete Independence)","Home Rule","Provincial Autonomy"], correct:1},
      {q:"Who presided over the 1929 Lahore Session of the Indian National Congress?", opts:["Mahatma Gandhi","Jawaharlal Nehru","Motilal Nehru","Subhas Chandra Bose"], correct:1},
      {q:"Who established the Indian Home Rule League at Pune in April 1916?", opts:["Annie Besant","Bal Gangadhar Tilak","Gopal Krishna Gokhale","Lala Lajpat Rai"], correct:1},
      {q:"In which year was the controversial Anarchical and Revolutionary Crimes Act (Rowlatt Act) passed?", opts:["1917","1919","1921","1923"], correct:1},
      {q:"What generic term did Indian leaders use to denounce the Rowlatt Act?", opts:["The Dark Act","The Black Act","The Tyranny Act","The Repression Act"], correct:1},
      {q:"Who founded the Ramakrishna Mission in 1897 at Belur Math?", opts:["Raja Ram Mohan Roy","Swami Vivekananda","Dayananda Saraswati","Keshab Chandra Sen"], correct:1},
      {q:"Which iconic Indian nationalist leader was honored with the title \"Lokmanya\"?", opts:["Gopal Krishna Gokhale","Bal Gangadhar Tilak","Lala Lajpat Rai","Bipin Chandra Pal"], correct:1},
      {q:"Who declared \"Swaraj is my birthright and I shall have it\"?", opts:["Mahatma Gandhi","Bal Gangadhar Tilak","Jawaharlal Nehru","Subhas Chandra Bose"], correct:1},
      {q:"Which influential Marathi newspaper was founded by Bal Gangadhar Tilak in 1881?", opts:["Kesari","Maratha","Amrita Bazar Patrika","Young India"], correct:0},
      {q:"Whom did Mahatma Gandhi explicitly regard as his political mentor (Political Guru)?", opts:["Bal Gangadhar Tilak","Gopal Krishna Gokhale","Dadabhai Naoroji","Surendranath Banerjee"], correct:1},
      {q:"In which year did Mahatma Gandhi permanently return to India from South Africa?", opts:["1911","1913","1915","1917"], correct:2},
      {q:"What was Mahatma Gandhi's very first satyagraha movement launched on Indian soil?", opts:["Kheda Satyagraha","Champaran Satyagraha","Ahmedabad Mill Strike","Bardoli Satyagraha"], correct:1},
      {q:"Who served as the final British Viceroy of India during the transition to independence in 1947?", opts:["Lord Wavell","Lord Mountbatten","Lord Linlithgow","Lord Irwin"], correct:1},
      {q:"What was the name of the official plan presented on 3rd June 1947 that outlined the partition of India?", opts:["Cripps Plan","Wavell Plan","Mountbatten Plan (3rd June Plan)","Cabinet Mission Plan"], correct:2},
      {q:"Who coined the popular nationalist slogan \"Quit India\"?", opts:["Mahatma Gandhi","Yusuf Meherally","Jawaharlal Nehru","Subhas Chandra Bose"], correct:1},
      {q:"At which famous venue in Mumbai was the Quit India Resolution formally passed by the AICC?", opts:["Shaniwarwada","Gowalia Tank Maidan (August Kranti Maidan)","Chowpatty Beach","Azad Maidan"], correct:1},
      {q:"Which nationalist leader and lawyer was affectionately known by the title \"Deshbandhu\"?", opts:["Chittaranjan Das (C. R. Das)","Motilal Nehru","Surendranath Banerjee","Bipin Chandra Pal"], correct:0},
      {q:"In which year were Bhagat Singh, Shivaram Rajguru, and Sukhdev Thapar executed by hanging?", opts:["1929","1930","1931","1932"], correct:2},
      {q:"On which date were Bhagat Singh, Rajguru, and Sukhdev executed in Lahore Jail?", opts:["23rd March 1931","23rd March 1930","30th January 1931","15th August 1931"], correct:0},
      {q:"Which Pashtun freedom fighter and nonviolent reformer was widely known as \"Frontier Gandhi\"?", opts:["Khan Abdul Ghaffar Khan","Maulana Abul Kalam Azad","Liaquat Ali Khan","Syed Ahmad Khan"], correct:0},
      {q:"Who wrote the seminal political booklet \"Hind Swaraj\" while traveling on a ship in 1909?", opts:["Mahatma Gandhi","Bal Gangadhar Tilak","Jawaharlal Nehru","Dadabhai Naoroji"], correct:0},
      {q:"Who was the first female recipient of India's highest civilian honor, the Bharat Ratna?", opts:["Indira Gandhi","Sarojini Naidu","Vijaya Lakshmi Pandit","Aruna Asaf Ali"], correct:0}
    ]},
    { title: "Modern History Set 4", questions: [
      {q:"Who popularized the Urdu slogan \"Inquilab Zindabad\" (Long Live the Revolution) during his trial and execution?", opts:["Chandrashekhar Azad","Bhagat Singh","Ram Prasad Bismil","Sukhdev"], correct:1},
      {q:"Which three prominent leaders formed the famous nationalist political grouping \"Lal-Bal-Pal\"?", opts:["Lala Lajpat Rai, Bal Gangadhar Tilak, and Bipin Chandra Pal","Lala Lajpat Rai, Bipin Chandra Pal, and Gokhale","Bal Gangadhar Tilak, Gokhale, and Bipin Chandra Pal","Lala Lajpat Rai, Bal Gangadhar Tilak, and Gokhale"], correct:0},
      {q:"What key status was promised to India by the British government through the Cripps Mission of 1942?", opts:["Full Independence","Dominion Status","Provincial Autonomy","Federal Status"], correct:1},
      {q:"What was the central marching call and battle cry of the Indian National Army?", opts:["Jai Hind","Chalo Dilli","Inquilab Zindabad","Vande Mataram"], correct:1},
      {q:"Which Prime Minister of India gave the iconic slogan \"Jai Jawan Jai Kisan\" during the 1965 war?", opts:["Jawaharlal Nehru","Lal Bahadur Shastri","Indira Gandhi","Morarji Desai"], correct:1},
      {q:"Who founded the reformist Hindu movement Arya Samaj in Mumbai in 1875?", opts:["Raja Ram Mohan Roy","Swami Dayanand Saraswati","Swami Vivekananda","Keshab Chandra Sen"], correct:1},
      {q:"Which reform movement was launched around the motto \"Back to the Vedas\"?", opts:["Brahmo Samaj","Arya Samaj","Ramakrishna Mission","Prarthana Samaj"], correct:1},
      {q:"Who was the first Indian as well as the first Asian to win a Nobel Prize in 1913?", opts:["C. V. Raman","Rabindranath Tagore","Mahatma Gandhi","Ronald Ross"], correct:1},
      {q:"In which category did Rabindranath Tagore win the Nobel Prize in 1913?", opts:["Peace","Physics","Literature","Economics"], correct:2},
      {q:"Which anthology of poetry earned Rabindranath Tagore the Nobel Prize in Literature?", opts:["Gitanjali","The Home and the World","Gora","Manasi"], correct:0},
      {q:"In which year did the Ilbert Bill controversy break out during the tenure of Lord Ripon?", opts:["1878","1883","1885","1892"], correct:1},
      {q:"How many lions are visible when viewing the official flat render of the National Emblem of India?", opts:["Two","Three","Four","One"], correct:1},
      {q:"What words are inscribed at the base of the National Emblem of India in Devanagari script?", opts:["Satyameva Jayate","Vande Mataram","Jai Hind","Dharma Chakra Pravartanaya"], correct:0},
      {q:"Which social reformer from South India started the \"Self-Respect Movement\" in 1925?", opts:["E. V. Ramasamy (Periyar)","C. N. Annadurai","Rajaji","Anna Hazare"], correct:0},
      {q:"Who was the British Prime Minister who sent the Cabinet Mission to India in 1946?", opts:["Winston Churchill","Clement Attlee","Neville Chamberlain","Stanley Baldwin"], correct:1},
      {q:"Which organization was founded by Raja Ram Mohan Roy in 1828 to promote monotheism and social reform?", opts:["Arya Samaj","Brahmo Samaj","Prarthana Samaj","Theosophical Society"], correct:1},
      {q:"From what city did the East India Company begin trading with India?", opts:["Surat, Gujarat","Bombay","Calcutta","Madras"], correct:0},
      {q:"Which city was the origin of the 1857 uprising on 10th May 1857?", opts:["Meerut, Uttar Pradesh","Delhi","Kanpur","Lucknow"], correct:0},
      {q:"The center of the national flag features a navy blue wheel. What does it stand for?", opts:["Sun and Prosperity","Ashoka Chakra (Wheel of Law and Dharma)","Wheel of Time","Wheel of Progress"], correct:1},
      {q:"The patriotic song \"Saare Jahan Se Achha\" was written by:", opts:["Rabindranath Tagore","Muhammad Iqbal","Bankim Chandra Chattopadhyay","Sarojini Naidu"], correct:1},
      {q:"In which year was the First Round Table Conference held in London?", opts:["1928","1930","1931","1932"], correct:1},
      {q:"When was the Purna Swaraj (Complete Independence) declaration promulgated by the Indian National Congress?", opts:["26th January 1930","15th August 1929","26th January 1929","31st December 1929"], correct:0},
      {q:"Which city in India is historically nicknamed \"City of Prime Ministers\"?", opts:["Prayagraj (Allahabad)","Lucknow","Varanasi","Kanpur"], correct:0},
      {q:"Which European power was the first to establish a direct sea trade route to India in 1498?", opts:["Portugal","Netherlands","France","Britain"], correct:0},
      {q:"On what date was New Delhi officially inaugurated as the new capital of India?", opts:["13th February 1931","26th January 1931","15th August 1931","1st April 1931"], correct:0}
    ]}, 
      { title: "Modern History Set 5", questions: [
  {q:"Which region of India saw the Moplah Rebellion?", opts:["Malabar region, Kerala","Coorg region, Karnataka","Rayalaseema region, Andhra","Konkan region, Maharashtra"], correct:0},
  {q:"What was the name of the mission that the British government dispatched to India in 1942 during World War II to enlist Indian support?", opts:["Cabinet Mission","Cripps Mission","Simon Mission","Wavell Mission"], correct:1},
  {q:"Which incident made the Chapekar Brothers famous in the Indian freedom struggle?", opts:["Bombing of the Central Assembly","Assassination of W. C. Rand in 1897","Kakori Train Robbery","Assassination of Michael O'Dwyer"], correct:1},
  {q:"In which city is the first fort constructed by the East India Company located?", opts:["Mumbai (Fort George)","Chennai (Fort St. George)","Kolkata (Fort William)","Surat (Fort Surat)"], correct:1},
  {q:"What was the title of the journal M.K. Gandhi published in English from 1919 to 1931?", opts:["Harijan","Young India","Indian Opinion","Navajivan"], correct:1},
  {q:"Which revolutionary died in Lahore jail as a result of a 63-day hunger strike?", opts:["Bhagat Singh","Jatin Das","Sukhdev","Chandrashekhar Azad"], correct:1},
  {q:"Who was the founder of the Indian National Congress?", opts:["Allan Octavian Hume","W. C. Bonnerjee","Dadabhai Naoroji","Surendranath Banerjee"], correct:0},
  {q:"Who was the leader of the Ramosi Peasant Force in Maharashtra in 1879?", opts:["Vasudev Balwant Phadke","Wasudeo Balwant","Tatya Tope","Nana Saheb"], correct:0},
  {q:"Which member of the independence movement was given the death penalty alongside Ram Prasad Bismil for the Kakori Train Robbery?", opts:["Ashfaqullah Khan","Roshan Singh","Rajendra Lahiri","Chandrashekhar Azad"], correct:0},
  {q:"Which Pakistani national received the Bharat Ratna award in 1987?", opts:["Liaquat Ali Khan","Khan Abdul Ghaffar Khan","Muhammad Ali Jinnah","Syed Ahmad Khan"], correct:1},
  {q:"Who served as the East India Company's first representative to the court of Mughal Emperor Jahangir in 1608?", opts:["Sir Thomas Roe","Captain William Hawkins","Robert Clive","Warren Hastings"], correct:1},
  {q:"What was the total number of provinces in British India at the time of independence?", opts:["11","14","17","20"], correct:2},
  {q:"Who was the primary mastermind behind Viceroy Lord Hardinge's assassination attempt in Delhi in 1912?", opts:["Rash Behari Bose","Sachin Sanyal","Bagha Jatin","Khudiram Bose"], correct:0},
  {q:"Who was in control of Goa before India annexed it in 1961?", opts:["The French","The Portuguese","The Dutch","The British"], correct:1},
  {q:"Which significant battle in 1757 established British East India Company rule in Bengal?", opts:["Battle of Buxar","Battle of Plassey","Battle of Wandiwash","Battle of Panipat"], correct:1},
  {q:"Who was British India's first Viceroy following the Government of India Act 1858?", opts:["Lord Canning","Lord Dalhousie","Lord Curzon","Lord Ripon"], correct:0},
  {q:"Who was the Ghadar Party's founding president in 1913?", opts:["Sohan Singh Bhakna","Lala Hardayal","Kartar Singh Sarabha","Bhagwan Singh"], correct:0},
  {q:"Which Indian revolutionary assassinated Michael O'Dwyer in London in 1940 to avenge the Jallianwala Bagh massacre?", opts:["Madan Lal Dhingra","Udham Singh","Bhagat Singh","Shivaram Rajguru"], correct:1},
  {q:"Which Indian revolutionary was the first to execute a British officer in England in 1909?", opts:["Udham Singh","Madan Lal Dhingra","V. D. Savarkar","Har Dayal"], correct:1},
  {q:"Who expounded the \"Drain of Wealth\" theory in his book \"Poverty and Un-British Rule in India\"?", opts:["Dadabhai Naoroji","R. C. Dutt","M. G. Ranade","Gopal Krishna Gokhale"], correct:0},
  {q:"Which port did the Komagata Maru ship dock at upon returning to India in September 1914?", opts:["Budge Budge Ghat, Kolkata","Chittagong","Vishakhapatnam","Nhava Sheva"], correct:0},
  {q:"Which revolutionary duo threw non-lethal bombs into the Central Legislative Assembly in Delhi in 1929?", opts:["Bhagat Singh and Batukeshwar Dutt","Bhagat Singh and Rajguru","Chandrashekhar Azad and Bhagat Singh","Sukhdev and Rajguru"], correct:0},
  {q:"Who was the primary founder of Banaras Hindu University in 1916?", opts:["Madan Mohan Malaviya","Motilal Nehru","Annie Besant","Lala Lajpat Rai"], correct:0},
  {q:"The book \"India Wins Freedom\" was written by:", opts:["Jawaharlal Nehru","Maulana Abul Kalam Azad","Rajendra Prasad","Sardar Patel"], correct:1},
  {q:"Which historical split divided the Indian National Congress into Moderates and Extremists in 1907?", opts:["Lahore Split","Surat Split","Calcutta Split","Lucknow Split"], correct:1}
 ]}, 
   { title: "Modern History Set 6", questions: [
  {q:"Which city in Punjab was the birthplace of revolutionary martyr Sukhdev Thapar?", opts:["Ludhiana","Amritsar","Jalandhar","Lahore"], correct:0},
  {q:"Who was the main founder and first commander of the original Indian National Army in 1942?", opts:["Captain Mohan Singh","Subhas Chandra Bose","Rash Behari Bose","Mohan Singh Deb"], correct:0},
  {q:"Who served as the president of the All-India Muslim League and led the campaign for Pakistan?", opts:["Liaquat Ali Khan","Muhammad Ali Jinnah","Syed Ahmad Khan","Choudhry Rahmat Ali"], correct:1},
  {q:"By whom was the Muhammadan Anglo-Oriental College (now Aligarh Muslim University) founded in 1875?", opts:["Sir Syed Ahmed Khan","Muhammad Ali Jinnah","Maulana Abul Kalam Azad","Aga Khan III"], correct:0},
  {q:"On which exact date was the Quit India Resolution adopted in Mumbai?", opts:["8th August 1942","9th August 1942","15th August 1942","3rd June 1942"], correct:0},
  {q:"Which Mughal ruler granted the East India Company a royal farman to establish permanent factories in Surat in 1612?", opts:["Akbar","Jahangir","Shah Jahan","Aurangzeb"], correct:1},
  {q:"Which social reformer collaborated with Lord William Bentinck to pass the Sati Abolition Act in 1829?", opts:["Raja Ram Mohan Roy","Ishwar Chandra Vidyasagar","Swami Dayanand Saraswati","Keshab Chandra Sen"], correct:0},
  {q:"Who wrote the famous essay \"Why I Am an Atheist\" while imprisoned in Lahore Central Jail?", opts:["Chandrashekhar Azad","Bhagat Singh","Sukhdev","Rajguru"], correct:1},
  {q:"What was the exact date of birth of Shaheed Bhagat Singh?", opts:["28th September 1907","23rd March 1907","15th August 1907","28th September 1909"], correct:0},
  {q:"Who laid the foundation stone of New Delhi during the Delhi Durbar of 1911?", opts:["King George V","Lord Hardinge","King Edward VII","Lord Curzon"], correct:0},
  {q:"Who was the primary British architect who designed master plans for New Delhi alongside Herbert Baker?", opts:["Sir Edwin Lutyens","Robert Tor Russell","William Emerson","Herbert Bloomfield"], correct:0},
  {q:"What group of soldiers does the India Gate memorial in New Delhi commemorate?", opts:["Freedom fighters of 1857","British Indian Army soldiers who died in World War I and the Third Anglo-Afghan War","Soldiers of the Indian National Army","Soldiers of World War II"], correct:1},
  {q:"Which former Prime Minister of India was awarded Pakistan's highest civilian honor, Nishan-e-Pakistan?", opts:["Jawaharlal Nehru","Morarji Desai","Indira Gandhi","Lal Bahadur Shastri"], correct:1},
  {q:"At which session of the Indian National Congress was the national song \"Vande Mataram\" sung for the first time?", opts:["1896 Calcutta Session","1885 Bombay Session","1907 Surat Session","1916 Lucknow Session"], correct:0},
  {q:"On what date did the Muslim League observe \"Direct Action Day\" in Kolkata?", opts:["16th August 1946","15th August 1946","3rd June 1947","9th August 1946"], correct:0},
  {q:"The Gateway of India in Mumbai was built to commemorate the arrival of which royal figure in December 1911?", opts:["King George V and Queen Mary","King Edward VII","Queen Victoria","King George VI"], correct:0},
  {q:"Who presided over the historic first session of the Indian National Congress held at Mumbai in 1885?", opts:["Allan Octavian Hume","Womesh Chunder Bonnerjee","Dadabhai Naoroji","Surendranath Banerjee"], correct:1},
  {q:"Who established the Indian Independence League in Tokyo in 1942?", opts:["Subhas Chandra Bose","Rash Behari Bose","Captain Mohan Singh","A. M. Sahay"], correct:1},
  {q:"Who remarked in his writings, \"Nehru is a patriot, while Jinnah is a politician\"?", opts:["Muhammad Iqbal","Rabindranath Tagore","Sarojini Naidu","Maulana Azad"], correct:0},
  {q:"Where was the decision taken to launch the Civil Disobedience Movement in February 1922 before its suspension?", opts:["Bardoli, Gujarat","Champaran, Bihar","Sabarmati, Gujarat","Chauri Chaura, UP"], correct:0},
  {q:"In which year was the Non-Cooperation Movement formally called off following the Chauri Chaura incident?", opts:["1920","1921","1922","1923"], correct:2},
  {q:"Which 1917 movement marked Mahatma Gandhi's first active satyagraha in Indian politics?", opts:["Kheda Satyagraha","Champaran Satyagraha","Ahmedabad Mill Strike","Bardoli Satyagraha"], correct:1},
  {q:"What was the first newspaper launched by the British committee of the Indian National Congress in London in 1889?", opts:["India","Young India","Free Hindustan","Indian Sociologist"], correct:0},
  {q:"Who founded the Ghadar Party in San Francisco in 1913 alongside Sohan Singh Bhakna?", opts:["Lala Har Dayal","Kartar Singh Sarabha","Bhagwan Singh","Ram Chandra"], correct:0},
  {q:"What official committee was appointed by the British government to investigate the Jallianwala Bagh massacre?", opts:["Hunter Commission","Rowlatt Commission","Simon Commission","Sadler Commission"], correct:0}
]}, 
    { title: "Modern History Set 7", questions: [
  {q:"Who was the first historian to describe the 1857 uprising as \"The Indian War of Independence\"?", opts:["Vinayak Damodar Savarkar","R. C. Majumdar","S. N. Sen","B. G. Tilak"], correct:0},
  {q:"Who was elected President of the All India Khilafat Conference held in Delhi in November 1919?", opts:["Maulana Abul Kalam Azad","Mahatma Gandhi","Shaukat Ali","Muhammad Ali Jauhar"], correct:1},
  {q:"Which classical musician performed the devotional hymn \"Raghupati Raghav Raja Ram\" during the Dandi March?", opts:["Vishnu Digambar Paluskar","Pandit Ravi Shankar","Ustad Allauddin Khan","Bhimsen Joshi"], correct:0},
  {q:"Who founded the All-India Harijan Sevak Sangh in 1932?", opts:["Mahatma Gandhi","B. R. Ambedkar","Jawaharlal Nehru","Vallabhbhai Patel"], correct:0},
  {q:"In which historic session of the Indian National Congress in 1916 did the Moderates and Extremists reunite?", opts:["Surat Session","Lucknow Session","Calcutta Session","Amritsar Session"], correct:1},
  {q:"Which violent incident in February 1922 led Mahatma Gandhi to suspend the Non-Cooperation Movement?", opts:["Jallianwala Bagh Massacre","Chauri Chaura Incident","Kakori Train Robbery","Champaran Incident"], correct:1},
  {q:"Whom did Subhas Chandra Bose defeat to win the INC Presidential election at the Tripuri session in 1939?", opts:["Pattabhi Sitaramayya","Rajendra Prasad","Vallabhbhai Patel","Jawaharlal Nehru"], correct:0},
  {q:"Who was declared the symbolic Emperor of India by the sepoys during the Revolt of 1857?", opts:["Bahadur Shah II (Bahadur Shah Zafar)","Nana Saheb","Tatya Tope","Mirza Mughal"], correct:0},
  {q:"In which session of the INC was the formal resolution for Purna Swaraj passed in December 1929?", opts:["Lahore Session","Karachi Session","Calcutta Session","Lucknow Session"], correct:0},
  {q:"Where was the Provisional Government of Free India (Azad Hind) officially proclaimed in October 1943?", opts:["Tokyo","Singapore","Rangoon","Berlin"], correct:1},
  {q:"Where and when was Jawaharlal Nehru's famous \"Tryst with Destiny\" speech delivered?", opts:["Red Fort, Delhi on 15th August 1947","Constituent Assembly, Parliament House, New Delhi on the midnight of 14th-15th August 1947","India Gate, Delhi on 26th January 1950","Gowalia Tank Maidan, Mumbai on 8th August 1942"], correct:1},
  {q:"Which freedom fighter succumbed to injuries sustained during a police lathi-charge while protesting the Simon Commission in Lahore?", opts:["Lala Lajpat Rai","Bhagat Singh","Chandrashekhar Azad","Bipin Chandra Pal"], correct:0},
  {q:"On the banks of which river in Lahore was the Indian Tricolor unfurled on New Year's Eve 1929?", opts:["Sutlej River","Ravi River","Beas River","Chenab River"], correct:1},
  {q:"Who was the first Indian elected to the British House of Commons in 1892?", opts:["Dadabhai Naoroji","Surendranath Banerjee","W. C. Bonnerjee","Gopal Krishna Gokhale"], correct:0},
  {q:"The Montagu-Chelmsford Reforms served as the basis for which major constitutional legislation?", opts:["Government of India Act 1909","Government of India Act 1919","Government of India Act 1935","Indian Councils Act 1892"], correct:1},
  {q:"Which constitutional act introduced the system of Executive Dyarchy in British Indian provinces?", opts:["Government of India Act 1909","Government of India Act 1919","Government of India Act 1935","Indian Councils Act 1861"], correct:1},
  {q:"Who founded the Servants of India Society in Pune in 1905?", opts:["Bal Gangadhar Tilak","Gopal Krishna Gokhale","Vinoba Bhave","M. G. Ranade"], correct:1},
  {q:"In which year was the Champaran Satyagraha carried out in Bihar?", opts:["1915","1917","1919","1920"], correct:1},
  {q:"Which movement was launched by Gandhi in 1918 to support indigo and crop-failure peasants in Gujarat?", opts:["Champaran Satyagraha","Kheda Satyagraha","Bardoli Satyagraha","Ahmedabad Mill Strike"], correct:1},
  {q:"In which month and year was the Indian Independence Act passed by the Parliament of the United Kingdom?", opts:["June 1947","July 1947","August 1947","May 1947"], correct:1},
  {q:"What was the name of the daily newspaper started by Jawaharlal Nehru in 1938?", opts:["National Herald","Young India","Harijan","The Leader"], correct:0},
  {q:"Which prominent parallel revolutionary government (Patri Sarkar) was formed under Chittu Pandey in 1942?", opts:["Tamluk Jatiya Sarkar","Ballia Parallel Government","Satara Prati Sarkar","Midnapore Parallel Government"], correct:1},
  {q:"Who operated the secret clandestine \"Congress Radio\" broadcast network during the Quit India Movement?", opts:["Usha Mehta","Aruna Asaf Ali","Sucheta Kripalani","Kamaladevi Chattopadhyay"], correct:0},
  {q:"Which legendary revolutionary woman is remembered as the \"Mother of the Indian Revolution\"?", opts:["Madame Bhikaji Cama","Kasturba Gandhi","Sarojini Naidu","Aruna Asaf Ali"], correct:0},
  {q:"In which foreign city did Madame Bhikaji Cama unfurl an early version of the Indian National Flag in 1907?", opts:["Stuttgart, Germany","Paris, France","London, England","Geneva, Switzerland"], correct:0}
]}, 
    { title: "Modern History Set 8", questions: [
  {q:"Which viceroy is popularly called the \"Father of Local Self-Government in India\"?", opts:["Lord Ripon","Lord Curzon","Lord Dalhousie","Lord Canning"], correct:0},
  {q:"Who was the first woman elected President of the United Nations General Assembly in 1953?", opts:["Sarojini Naidu","Vijaya Lakshmi Pandit","Indira Gandhi","Annie Besant"], correct:1},
  {q:"Who served as the founding president of the All India Trade Union Congress (AITUC) in 1920?", opts:["Lala Lajpat Rai","N. M. Joshi","Motilal Nehru","Diwan Chaman Lall"], correct:0},
  {q:"Which revolutionary organization was established at Feroz Shah Kotla, Delhi in 1928 by Chandrashekhar Azad and Bhagat Singh?", opts:["Anushilan Samiti","Hindustan Socialist Republican Association (HSRA)","Ghadar Party","Abhinav Bharat Society"], correct:1},
  {q:"Who was the reorganization leader and supreme commander of the HSRA after 1928?", opts:["Bhagat Singh","Chandrashekhar Azad","Sukhdev","Ram Prasad Bismil"], correct:1},
  {q:"Who led the daring raid on the British police armoury at Chittagong in April 1930?", opts:["Surya Sen","Pritilata Waddedar","Ganesh Ghosh","Ananta Singh"], correct:0},
  {q:"What popular honorary name was revolutionary leader Surya Sen known by among his followers?", opts:["Masterda","Netaji","Deshbandhu","Lokmanya"], correct:0},
  {q:"What was the popular Pashtun nonviolent movement established by Khan Abdul Ghaffar Khan in 1929?", opts:["Khudai Khidmatgar (Red Shirts)","Ahrar Movement","Khilafat Movement","Anjuman-e-Islamia"], correct:0},
  {q:"In what year was Mahatma Gandhi's book \"Hind Swaraj\" published?", opts:["1905","1909","1915","1920"], correct:1},
  {q:"Who originally penned the slogan \"Inquilab Zindabad\" in 1921?", opts:["Bhagat Singh","Hasrat Mohani","Maulana Azad","Ram Prasad Bismil"], correct:1},
  {q:"Who served as the long-time president of the Theosophical Society based at Adyar, Chennai?", opts:["Annie Besant","Madame Blavatsky","Henry Steel Olcott","Sarojini Naidu"], correct:0},
  {q:"What weekly newspaper was edited by Mahatma Gandhi during his civil rights work in South Africa?", opts:["Young India","Indian Opinion","Harijan","Navajivan"], correct:1},
  {q:"Who was the Prime Minister of the United Kingdom during the dispatch of the Cripps Mission in 1942?", opts:["Neville Chamberlain","Winston Churchill","Clement Attlee","Stanley Baldwin"], correct:1},
  {q:"Who were the three British Cabinet members who constituted the Cabinet Mission to India in 1946?", opts:["Lord Pethick-Lawrence, Sir Stafford Cripps, and A. V. Alexander","Lord Wavell, Stafford Cripps, and Clement Attlee","Lord Pethick-Lawrence, Lord Wavell, and A. V. Alexander","Stafford Cripps, A. V. Alexander, and Lord Linlithgow"], correct:0},
  {q:"Who served as the first Chief Justice of the Federal Court and later the Supreme Court of Independent India?", opts:["M. Patanjali Sastri","Harilal Jekisundas Kania","B. K. Mukherjea","S. R. Das"], correct:1},
  {q:"Which freedom fighter and reformer was popularly addressed with the prefix title \"Veer\"?", opts:["Vinayak Damodar Savarkar","Bhagat Singh","Chandrashekhar Azad","Khudiram Bose"], correct:0},
  {q:"Who was the only Congress President to resign from office due to ideological differences with Mahatma Gandhi?", opts:["Jawaharlal Nehru","Subhas Chandra Bose","Rajendra Prasad","C. R. Das"], correct:1},
  {q:"Who served as the commander of the all-women 'Rani of Jhansi Regiment' of the Indian National Army?", opts:["Captain Lakshmi Sahgal","Aruna Asaf Ali","Usha Mehta","Sarojini Naidu"], correct:0},
  {q:"In which year did Subhas Chandra Bose take over and reorganize the Indian National Army in East Asia?", opts:["1941","1942","1943","1944"], correct:2},
  {q:"Who was the British Governor-General who abolished the practice of Sati in 1829?", opts:["Lord William Bentinck","Lord Dalhousie","Lord Canning","Lord Ripon"], correct:0},
  {q:"Who was the commander-in-chief of the rebel forces in Kanpur during the 1857 Revolt?", opts:["Bahadur Shah Zafar","Nana Saheb (assisted by Tatya Tope)","Rani Lakshmibai","Begum Hazrat Mahal"], correct:1},
  {q:"Where was Mahatma Gandhi placed under house arrest following the launch of the Quit India Movement in 1942?", opts:["Yerwada Central Jail, Pune","Aga Khan Palace, Pune","Naini Central Jail, Allahabad","Ahmednagar Fort"], correct:1},
  {q:"Who was chosen by Mahatma Gandhi as the very first Individual Satyagrahi in October 1940?", opts:["Jawaharlal Nehru","Acharya Vinoba Bhave","Sardar Patel","Rajendra Prasad"], correct:1},
  {q:"Who was the second leader to offer Individual Satyagraha after Vinoba Bhave in 1940?", opts:["Jawaharlal Nehru","Sardar Patel","C. Rajagopalachari","Rajendra Prasad"], correct:0},
  {q:"On which date was the Constitution of India formally adopted by the Constituent Assembly before coming into effect in 1950?", opts:["26th November 1949","15th August 1947","26th January 1949","2nd October 1949"], correct:0}
]},
    { title: "Modern History Set 9", questions: [
  {q:"Which Portuguese explorer arrived at Calicut in 1498, opening direct European trade with India?", opts:["Vasco da Gama","Pedro Alvares Cabral","Ferdinand Magellan","Bartolomeu Dias"], correct:0},
  {q:"Who was the last British Governor-General of India before the office was replaced by the President of India?", opts:["Lord Mountbatten","C. Rajagopalachari","Lord Wavell","Lord Linlithgow"], correct:1},
  {q:"In which year was the Vernacular Press Act passed by Viceroy Lord Lytton?", opts:["1870","1875","1878","1882"], correct:2},
  {q:"Who was the founder of the Indian Association established in 1876 in Kolkata?", opts:["Surendranath Banerjee and Ananda Mohan Bose","W. C. Bonnerjee and Allan Octavian Hume","Dadabhai Naoroji and Pherozeshah Mehta","Rajendralal Mitra and Bhudev Mukhopadhyay"], correct:0},
  {q:"Which revolutionary paper was published in Paris by Madame Bhikaji Cama?", opts:["Vande Mataram","Bande Mataram","Talwar","Free Hindustan"], correct:0},
  {q:"Who was known as the \"Heroine of 1942\" for hoisting the Indian National Congress flag at Gowalia Tank Maidan?", opts:["Usha Mehta","Aruna Asaf Ali","Sucheta Kripalani","Kamaladevi Chattopadhyay"], correct:1},
  {q:"Who founded the Anushilan Samiti, a prominent revolutionary group in Bengal, in 1902?", opts:["Pramathanath Mitra","Barindra Kumar Ghosh","Jatindranath Mukherjee","Bagha Jatin"], correct:0},
  {q:"Which British officer was assassinated by Bhagat Singh and Rajguru to avenge the death of Lala Lajpat Rai?", opts:["Michael O'Dwyer","John Saunders","James Scott","Reginald Dyer"], correct:1},
  {q:"What was the venue of the Second Round Table Conference held in 1931?", opts:["St. James's Palace, London","Buckingham Palace, London","Westminster Hall, London","10 Downing Street, London"], correct:0},
  {q:"Who was the only Indian representative to attend all three Round Table Conferences alongside Dr. B. R. Ambedkar?", opts:["Tej Bahadur Sapru","Muhammad Ali Jinnah","Madan Mohan Malaviya","Mirabehn"], correct:0},
  {q:"Which treaty ended the First Anglo-Sikh War in 1846?", opts:["Treaty of Amritsar","Treaty of Lahore","Treaty of Bassein","Treaty of Sagauli"], correct:1},
  {q:"Who founded the \"Abhinav Bharat Society\" in 1904?", opts:["Vinayak Damodar Savarkar and Ganesh Damodar Savarkar","Bal Gangadhar Tilak and Gokhale","Chandrashekhar Azad and Bhagat Singh","Khudiram Bose and Prafulla Chaki"], correct:0},
  {q:"In which year was the Permanent Settlement of Bengal introduced by Lord Cornwallis?", opts:["1773","1784","1793","1805"], correct:2},
  {q:"Who was the first Indian to join the Indian Civil Service (ICS) in 1863?", opts:["Satyendranath Tagore","Surendranath Banerjee","R. C. Dutt","Subhas Chandra Bose"], correct:0},
  {q:"Which peasant movement in Gujarat in 1928 earned Vallabhbhai Patel the title \"Sardar\"?", opts:["Kheda Satyagraha","Bardoli Satyagraha","Champaran Satyagraha","Borsad Satyagraha"], correct:1},
  {q:"Who was the author of the patriotic poem \"Kadam Kadam Badaye Ja\"?", opts:["Ramsingh Thakuri","Mumtaz Hussain","Vande Mataram Ram Singh","Subhas Chandra Bose"], correct:0},
  {q:"In which city was the headquarters of the Ghadar Party located?", opts:["San Francisco, USA","New York, USA","London, UK","Vancouver, Canada"], correct:0},
  {q:"Who was the British Prime Minister who announced the \"Communal Award\" in 1932?", opts:["Ramsay MacDonald","Stanley Baldwin","Winston Churchill","Neville Chamberlain"], correct:0},
  {q:"Where did Mahatma Gandhi sign the historic Poona Pact with Dr. B. R. Ambedkar in 1932?", opts:["Sabarmati Ashram, Ahmedabad","Yerwada Central Jail, Pune","Aga Khan Palace, Pune","Naini Central Jail"], correct:1},
  {q:"Who was the Commander-in-Chief of the East India Company forces during the Battle of Buxar in 1764?", opts:["Robert Clive","Hector Munro","Warren Hastings","Eyre Coote"], correct:1},
  {q:"Which female revolutionary shot the Bengal Governor Stanley Jackson during her convocation ceremony in 1932?", opts:["Bina Das","Pritilata Waddedar","Kalpana Dutt","Suhasini Ganguly"], correct:0},
  {q:"Who founded the Deccan Education Society in Pune in 1884?", opts:["Gopal Ganesh Agarkar, Bal Gangadhar Tilak, and Vishnushastri Chiplunkar","Mahadev Govind Ranade and Gokhale","Jyotiba Phule and Savitribai Phule","Vishnu Shastri Pandit and Tilak"], correct:0},
  {q:"What was the real name of Swami Vivekananda?", opts:["Narendranath Datta","Gadadhar Chattopadhyay","Keshab Chandra Sen","Bipin Chandra Pal"], correct:0},
  {q:"Which movement was started by Swami Dayanand Saraswati to bring converted individuals back to Hinduism?", opts:["Shuddhi Movement","Sangathan Movement","Arya Samaj Reform","Back to Vedas Movement"], correct:0},
  {q:"Who was the Viceroy of India when the Jallianwala Bagh massacre occurred in 1919?", opts:["Lord Chelmsford","Lord Reading","Lord Irwin","Lord Willingdon"], correct:0}
]}, 
    { title: "Modern History Set 10", questions: [
  {q:"In which year was the Partition of Bengal officially revoked by Lord Hardinge?", opts:["1908","1911","1913","1915"], correct:1},
  {q:"Who was the chief editor of the English daily \"Amrita Bazar Patrika\" during the anti-partition movement?", opts:["Sisir Kumar Ghosh","Surendranath Banerjee","Motilal Ghosh","Bipin Chandra Pal"], correct:0},
  {q:"What was the name of the secret military operation conducted to annex Hyderabad into the Indian Union in 1948?", opts:["Operation Polo","Operation Vijay","Operation Meghdoot","Operation Cactus"], correct:0},
  {q:"Who served as the Deputy Prime Minister in the first cabinet of independent India?", opts:["Rajendra Prasad","Sardar Vallabhbhai Patel","C. Rajagopalachari","Jawaharlal Nehru"], correct:1},
  {q:"Who authored the famous book \"Gulamgiri\" published in 1873?", opts:["Jyotirao Phule","B. R. Ambedkar","Periyar E. V. Ramasamy","Savitribai Phule"], correct:0},
  {q:"Which social reform society was founded by Jyotirao Phule in Maharashtra in 1873?", opts:["Prarthana Samaj","Satyashodhak Samaj","Arya Samaj","Brahmo Samaj"], correct:1},
  {q:"Who was the leader of the Santhal Rebellion of 1855 against British rule and zamindars?", opts:["Sidhu and Kanhu Murmu","Birsa Munda","Tantia Bhil","Alluri Sitarama Raju"], correct:0},
  {q:"In which year did the Kakori Train Action take place?", opts:["1921","1923","1925","1928"], correct:2},
  {q:"Who was the defense lawyer for the accused Indian National Army officers during the famous Red Fort Trials in 1945?", opts:["Bhulabhai Desai","Tej Bahadur Sapru","Asaf Ali","Jawaharlal Nehru"], correct:0},
  {q:"Who led the famous Paika Rebellion against the British East India Company in Odisha in 1817?", opts:["Bakshi Jagabandhu","Surendra Sai","Laxman Naik","Raja Ram Chandra Dev"], correct:0},
  {q:"Which British monarch was the first to visit India after the Crown took over governance?", opts:["Queen Victoria","King Edward VII","King George V","King George VI"], correct:2},
  {q:"Who founded the Bharat Mata Society in 1904 at Lahore?", opts:["Ajit Singh and Sufi Amba Prasad","Lala Lajpat Rai and Bhagat Singh","Sardar Ajit Singh alone","Kishan Singh and Lala Lajpat Rai"], correct:0},
  {q:"What was the main reason for the launch of the Individual Satyagraha in 1940?", opts:["To demand complete independence immediately","To protest against India being dragged into World War II without its consent","To oppose the Rowlatt Act","To protest the Partition of Bengal"], correct:1},
  {q:"Who led the Salt Satyagraha along the Malabar Coast from Calicut to Payyanur?", opts:["K. Kelappan","C. Rajagopalachari","K. Madhavan Nair","Muthuranga Mudaliar"], correct:0},
  {q:"In which session did the INC adopt the resolution on Fundamental Rights and Economic Policy?", opts:["1929 Lahore Session","1931 Karachi Session","1936 Faizpur Session","1938 Haripura Session"], correct:1},
  {q:"Who presided over the 1931 Karachi Session of the Indian National Congress?", opts:["Jawaharlal Nehru","Sardar Vallabhbhai Patel","Mahatma Gandhi","Subhas Chandra Bose"], correct:1},
  {q:"Who was the British Governor-General who introduced the policy of \"Doctrine of Lapse\"?", opts:["Lord Dalhousie","Lord Canning","Lord William Bentinck","Lord Hardinge"], correct:0},
  {q:"Which kingdom was the first to be annexed under the Doctrine of Lapse in 1848?", opts:["Jhansi","Satara","Nagpur","Awadh"], correct:1},
  {q:"Who was the British monarch when India gained independence in 1947?", opts:["King George V","King Edward VIII","King George VI","Queen Elizabeth II"], correct:2},
  {q:"What was the name of the journal started by Dr. B. R. Ambedkar in 1920?", opts:["Mooknayak","Bahishkrit Bharat","Janata","Equality Janta"], correct:0},
  {q:"Who founded the \"Bahishkrit Hitakarini Sabha\" in 1924 to promote education and socio-economic upliftment of Dalits?", opts:["Jyotirao Phule","Dr. B. R. Ambedkar","Periyar E. V. Ramasamy","Mahatma Gandhi"], correct:1},
  {q:"Which battle in 1760 marked the decisive defeat of the French forces by the British in India?", opts:["Battle of Plassey","Battle of Wandiwash","Battle of Buxar","Battle of Panipat"], correct:1},
  {q:"Who was the leader of the Uprising of 1857 in Bihar?", opts:["Kunwar Singh","Rani Lakshmibai","Nana Saheb","Tatya Tope"], correct:0},
  {q:"Which newspaper was started by Motilal Nehru in 1919 from Allahabad?", opts:["National Herald","The Independent","The Leader","Young India"], correct:1},
  {q:"Who was the founder of the Central Hindu College in Varanasi in 1898?", opts:["Madan Mohan Malaviya","Annie Besant","Swami Dayanand Saraswati","Swami Vivekananda"], correct:1}
]}
  ]
};

